---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  template:
    spec:
      containers:
        - name: main
          image: busybox:latest
          command: ['sleep', '3600']
          envFrom:
            - configMapRef:
                name: envs
          volumeMounts:
            - name: from-configmap-volume
              mountPath: /etc/file.txt
              subPath: file1.txt
        - { 'name': 'dnsmasq', 'image': 'andyshinn/dnsmasq:2.78', 'command': ['dnsmasq', '-k', '--log-facility=-'], 'securityContext': { 'capabilities': { 'add': ['NET_ADMIN'] } } }
      volumes:
        - name: from-configmap-volume
          configMap:
            name: files
